apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: lumander-next-js
  app.kubernetes.io/instance: lumander-next-js-instance
  app.kubernetes.io/name: lumander-next-js
