apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample
    app.kubernetes.io/instance: sample-instance
    app.kubernetes.io/name: sample
  name: sample
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: sample-instance
    app.kubernetes.io/name: sample
  sessionAffinity: None
  type: ClusterIP
